"""create models

Revision ID: 60b5d5e8c3c5
Revises:
Create Date: 2025-11-02 17:00:30.875623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60b5d5e8c3c5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Название деятельности",
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "level",
            sa.Integer(),
            nullable=False,
            comment="Уровень вложенности",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["activities.id"],
            name=op.f("fk_activities_parent_id_activities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(
        op.f("ix_activities_level"), "activities", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_activities_parent_id"),
        "activities",
        ["parent_id"],
        unique=False,
    )
    op.create_table(
        "buildings",
        sa.Column(
            "address",
            sa.String(length=512),
            nullable=False,
            comment="Адрес здания",
        ),
        sa.Column(
            "latitude",
            sa.Float(precision=10),
            nullable=False,
            comment="Широта",
        ),
        sa.Column(
            "longitude",
            sa.Float(precision=10),
            nullable=False,
            comment="Долгота",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buildings")),
    )
    op.create_table(
        "organizations",
        sa.Column(
            "name",
            sa.String(length=256),
            nullable=False,
            comment="Название организации",
        ),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_organizations_building_id_buildings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations_building_id"),
        "organizations",
        ["building_id"],
        unique=False,
    )
    op.create_table(
        "organization_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_organization_activities_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_organization_activities_organization_id_organizations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_activities")),
        sa.UniqueConstraint(
            "organization_id", "activity_id", name="uq_organization_activity"
        ),
        comment="Связь многие-ко-многим между организациями и видами деятельности",
    )
    op.create_index(
        op.f("ix_organization_activities_activity_id"),
        "organization_activities",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_activities_organization_id"),
        "organization_activities",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "phone_numbers",
        sa.Column(
            "number",
            sa.String(length=11),
            nullable=False,
            comment="Номер телефона в формате 79991234567",
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_phone_numbers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_numbers")),
    )
    op.create_index(
        op.f("ix_phone_numbers_organization_id"),
        "phone_numbers",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_phone_numbers_organization_id"), table_name="phone_numbers"
    )
    op.drop_table("phone_numbers")
    op.drop_index(
        op.f("ix_organization_activities_organization_id"),
        table_name="organization_activities",
    )
    op.drop_index(
        op.f("ix_organization_activities_activity_id"),
        table_name="organization_activities",
    )
    op.drop_table("organization_activities")
    op.drop_index(
        op.f("ix_organizations_building_id"), table_name="organizations"
    )
    op.drop_table("organizations")
    op.drop_table("buildings")
    op.drop_index(op.f("ix_activities_parent_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_level"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
