"""create models

Revision ID: 178ff7b02401
Revises:
Create Date: 2025-09-23 08:26:32.699794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "178ff7b02401"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Название деятельности",
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "level_parent",
            sa.Integer(),
            nullable=False,
            comment="Уровень вложенности",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["activities.id"],
            name=op.f("fk_activities_parent_id_activities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_table(
        "buildings",
        sa.Column(
            "address", sa.String(), nullable=False, comment="Адрес здания"
        ),
        sa.Column("latitude", sa.Float(), nullable=False, comment="Широта"),
        sa.Column("longitude", sa.Float(), nullable=False, comment="Долгота"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buildings")),
    )
    op.create_table(
        "organizations",
        sa.Column(
            "name", sa.String(), nullable=False, comment="Название организации"
        ),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_organizations_building_id_buildings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "organization_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_organization_activities_activity_id_activities"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_organization_activities_organization_id_organizations"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_activities")),
        sa.UniqueConstraint(
            "organization_id",
            "activity_id",
            name="idx_unique_organization_activity",
        ),
    )
    op.create_table(
        "phone_numbers",
        sa.Column(
            "number",
            sa.String(length=11),
            nullable=False,
            comment="Номер телефона",
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_phone_numbers_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_numbers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("phone_numbers")
    op.drop_table("organization_activities")
    op.drop_table("organizations")
    op.drop_table("buildings")
    op.drop_table("activities")
    # ### end Alembic commands ###
